import type { LegalUpdate } from './store/legal-updates-store';

/**
 * 法令・制度更新のデモデータ
 * 2024-2025年の実際の法改正を参考にしたリアルなデータ
 */
export const demoLegalUpdates: Omit<LegalUpdate, 'id' | 'createdAt' | 'updatedAt'>[] = [
  // 2024年 適用済み
  {
    title: '定額減税制度の開始',
    category: 'tax',
    effectiveDate: '2024-06-01',
    status: 'applied',
    importance: 'critical',
    description: '令和6年分所得税・個人住民税の定額減税が実施されました。所得税3万円、個人住民税1万円（本人・配偶者・扶養親族1人につき）の減税が適用されます。',
    beforeContent: '定額減税制度なし',
    afterContent: '所得税3万円、住民税1万円の定額減税を実施。給与支払時に順次控除。',
    affectedAreas: ['給与計算', '年末調整', '源泉徴収'],
    lawName: '所得税法等の一部を改正する法律',
    referenceUrl: 'https://www.nta.go.jp/users/gensen/teigakugenzei/index.htm',
    systemUpdated: true,
    systemUpdateDetails: '給与計算システムに定額減税の自動計算機能を実装済み。2024年6月給与から適用開始。',
    createdBy: 'システム管理者',
  },
  {
    title: '社会保険料率の改定（令和6年度）',
    category: 'social_insurance',
    effectiveDate: '2024-03-01',
    status: 'applied',
    importance: 'high',
    description: '令和6年度の健康保険料率・介護保険料率が改定されました。協会けんぽの健康保険料率は都道府県ごとに異なります。',
    beforeContent: '健康保険料率: 10.00%（全国平均）\n介護保険料率: 1.82%',
    afterContent: '健康保険料率: 10.00%（全国平均）\n介護保険料率: 1.60%',
    affectedAreas: ['給与計算', '社会保険手続き'],
    lawName: '健康保険法',
    referenceUrl: 'https://www.kyoukaikenpo.or.jp/g7/cat330/sb3130/r06/r6ryougakuhyou/',
    systemUpdated: true,
    systemUpdateDetails: '社会保険料率マスタを更新済み。2024年3月給与から新料率で自動計算。',
    createdBy: 'システム管理者',
  },
  {
    title: '障害者法定雇用率の引き上げ（2.5%）',
    category: 'labor',
    effectiveDate: '2024-04-01',
    status: 'applied',
    importance: 'high',
    description: '民間企業の障害者法定雇用率が2.3%から2.5%に引き上げられました。従業員40人以上の企業が対象です。',
    beforeContent: '法定雇用率: 2.3%（従業員43.5人以上が対象）',
    afterContent: '法定雇用率: 2.5%（従業員40人以上が対象）',
    affectedAreas: ['人事管理', '雇用管理'],
    lawName: '障害者の雇用の促進等に関する法律',
    referenceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/shougaishakoyou/index.html',
    systemUpdated: true,
    systemUpdateDetails: '障害者雇用状況管理機能に新基準を適用済み。',
    createdBy: 'システム管理者',
  },
  {
    title: '労働条件明示ルールの強化',
    category: 'labor',
    effectiveDate: '2024-04-01',
    status: 'applied',
    importance: 'high',
    description: '労働契約締結時・有期労働契約更新時の労働条件明示事項が追加されました。就業場所・業務の変更範囲、更新上限の明示が義務化されました。',
    beforeContent: '基本的な労働条件の明示のみ',
    afterContent: '就業場所・業務の変更範囲、更新上限（有期契約の場合）の明示を追加',
    affectedAreas: ['労働契約管理', '雇用契約書'],
    lawName: '労働基準法施行規則',
    referenceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000099951.html',
    systemUpdated: true,
    systemUpdateDetails: '雇用契約書テンプレートに必須項目を追加済み。',
    createdBy: 'システム管理者',
  },

  // 2024年 予定
  {
    title: '障害者法定雇用率のさらなる引き上げ（2.7%）',
    category: 'labor',
    effectiveDate: '2026-07-01',
    status: 'scheduled',
    importance: 'high',
    description: '民間企業の障害者法定雇用率が2.7%に段階的に引き上げられます。',
    beforeContent: '法定雇用率: 2.5%',
    afterContent: '法定雇用率: 2.7%',
    affectedAreas: ['人事管理', '雇用管理'],
    lawName: '障害者の雇用の促進等に関する法律',
    referenceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/koyou/shougaishakoyou/index.html',
    systemUpdated: false,
    createdBy: 'システム管理者',
  },

  // 2025年 予定
  {
    title: '雇用保険料率の改定（令和7年度）',
    category: 'social_insurance',
    effectiveDate: '2025-04-01',
    status: 'preparing',
    importance: 'medium',
    description: '令和7年度の雇用保険料率改定が予定されています。詳細は令和7年2月頃に発表予定です。',
    beforeContent: '雇用保険料率: 労働者負担 0.6%、事業主負担 0.95%',
    afterContent: '未定（2月頃発表予定）',
    affectedAreas: ['給与計算', '雇用保険手続き'],
    lawName: '雇用保険法',
    referenceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000108634.html',
    systemUpdated: false,
    createdBy: 'システム管理者',
  },
  {
    title: '年収の壁・支援強化パッケージの継続',
    category: 'social_insurance',
    effectiveDate: '2025-10-01',
    status: 'scheduled',
    importance: 'medium',
    description: '年収106万円・130万円の壁への対応として、社会保険適用促進手当の標準報酬算定除外措置が継続されます。',
    beforeContent: '手当を含めた総額で社会保険料算定',
    afterContent: '社会保険適用促進手当（上限月額5万円）を標準報酬から除外（最大2年間）',
    affectedAreas: ['給与計算', '社会保険手続き'],
    lawName: '健康保険法・厚生年金保険法',
    referenceUrl: 'https://www.mhlw.go.jp/stf/taiou_001_00002.html',
    systemUpdated: false,
    createdBy: 'システム管理者',
  },

  // 年末調整関連
  {
    title: '令和6年分 年末調整の変更点',
    category: 'tax',
    effectiveDate: '2024-12-01',
    status: 'preparing',
    importance: 'critical',
    description: '令和6年分の年末調整では、定額減税の精算を含む調整が必要です。また、扶養控除等申告書の様式が一部変更されています。',
    beforeContent: '通常の年末調整手続き',
    afterContent: '定額減税の年調減税額の計算・精算を追加。扶養控除等申告書の様式変更（国外居住親族関係書類の添付義務化範囲拡大）',
    affectedAreas: ['年末調整', '給与計算', '源泉徴収'],
    lawName: '所得税法',
    referenceUrl: 'https://www.nta.go.jp/users/gensen/nencho/index.htm',
    systemUpdated: false,
    systemUpdateDetails: '年末調整システムに定額減税精算機能を実装中。11月リリース予定。',
    createdBy: 'システム管理者',
  },

  // 労働時間関連
  {
    title: '時間外労働の上限規制（建設業・自動車運転業等）',
    category: 'attendance',
    effectiveDate: '2024-04-01',
    status: 'applied',
    importance: 'critical',
    description: '建設業、自動車運転業、医師等にも時間外労働の上限規制が適用開始されました。原則月45時間・年360時間、特別条項でも年720時間以内等の制限があります。',
    beforeContent: '上限規制の適用猶予',
    afterContent: '時間外労働の上限: 原則月45時間・年360時間。特別条項適用時も年720時間、複数月平均80時間、月100時間未満',
    affectedAreas: ['勤怠管理', '労働時間管理', '36協定'],
    lawName: '労働基準法',
    referenceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/roudoukijun/gyosyu/shokatsu/index.html',
    systemUpdated: true,
    systemUpdateDetails: '勤怠管理システムに上限規制チェック機能を実装済み。超過アラート機能も追加。',
    createdBy: 'システム管理者',
  },
  {
    title: '月60時間超の時間外労働割増率引き上げ',
    category: 'payroll',
    effectiveDate: '2023-04-01',
    status: 'applied',
    importance: 'high',
    description: '中小企業における月60時間超の時間外労働の割増賃金率が25%から50%に引き上げられました。',
    beforeContent: '月60時間超の時間外労働: 25%割増',
    afterContent: '月60時間超の時間外労働: 50%割増',
    affectedAreas: ['給与計算', '勤怠管理'],
    lawName: '労働基準法',
    referenceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/roudoukijun/roudouzikan/index.html',
    systemUpdated: true,
    systemUpdateDetails: '給与計算システムの割増率計算ロジックを更新済み。',
    createdBy: 'システム管理者',
  },

  // その他
  {
    title: 'デジタル給与払いの解禁',
    category: 'payroll',
    effectiveDate: '2023-04-01',
    status: 'applied',
    importance: 'medium',
    description: '労働者の同意を得た場合、指定資金移動業者の口座への賃金支払いが可能になりました。',
    beforeContent: '銀行口座または現金払いのみ',
    afterContent: '労働者の同意のもと、指定資金移動業者（PayPay、楽天ペイ等）への支払いが可能',
    affectedAreas: ['給与計算', '給与支払い'],
    lawName: '労働基準法施行規則',
    referenceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/koyou_roudou/roudoukijun/zigyonushi/shienjigyou/03.html',
    systemUpdated: false,
    systemUpdateDetails: '将来的な対応を検討中。現時点では従来の銀行振込のみ対応。',
    createdBy: 'システム管理者',
  },
  {
    title: '育児休業取得状況の公表義務化',
    category: 'labor',
    effectiveDate: '2023-04-01',
    status: 'applied',
    importance: 'medium',
    description: '従業員数1,000人超の企業に対して、育児休業取得状況の年1回の公表が義務付けられました。',
    beforeContent: '公表義務なし',
    afterContent: '従業員1,000人超の企業は、男性の育児休業取得率等を年1回公表',
    affectedAreas: ['人事管理', '労務管理'],
    lawName: '育児・介護休業法',
    referenceUrl: 'https://www.mhlw.go.jp/stf/seisakunitsuite/bunya/0000130583.html',
    systemUpdated: true,
    systemUpdateDetails: '育児休業取得状況レポート機能を実装済み。',
    createdBy: 'システム管理者',
  },
];

/**
 * デモデータをストアに初期化する関数
 */
export function initializeLegalUpdatesDemo(addUpdate: (update: Omit<LegalUpdate, 'id' | 'createdAt' | 'updatedAt'>) => void) {
  demoLegalUpdates.forEach((update) => {
    addUpdate(update);
  });
}
