/**
 * ユーザー管理用のモックデータ生成
 */

import type { User } from '@/types';

/**
 * モックユーザーデータ（SaaS割り当て用）
 */
export const mockUsers: User[] = [
  {
    id: 'user-1',
    tenantId: 'tenant-demo-001',
    name: '田中太郎',
    email: 'tanaka@example.com',
    department: '開発部',
    position: 'リーダー',
    roles: ['employee'],
    status: 'active',
    phone: '090-1234-5001',
    hireDate: '2020-04-01',
    unitId: 'unit-1',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-2',
    tenantId: 'tenant-demo-001',
    name: '佐藤花子',
    email: 'sato@example.com',
    department: '開発部',
    position: 'エンジニア',
    roles: ['employee'],
    status: 'active',
    phone: '090-1234-5002',
    hireDate: '2021-04-01',
    unitId: 'unit-1',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-3',
    tenantId: 'tenant-demo-001',
    name: '鈴木一郎',
    email: 'suzuki@example.com',
    department: '営業部',
    position: 'マネージャー',
    roles: ['manager'],
    status: 'active',
    phone: '090-1234-5003',
    hireDate: '2019-04-01',
    unitId: 'unit-2',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-4',
    tenantId: 'tenant-demo-001',
    name: '山田美咲',
    email: 'yamada@example.com',
    department: '営業部',
    position: '主任',
    roles: ['employee'],
    status: 'active',
    phone: '090-1234-5004',
    hireDate: '2020-10-01',
    unitId: 'unit-2',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-5',
    tenantId: 'tenant-demo-001',
    name: '伊藤健太',
    email: 'ito@example.com',
    department: '総務部',
    position: '課長',
    roles: ['manager'],
    status: 'active',
    phone: '090-1234-5005',
    hireDate: '2018-04-01',
    unitId: 'unit-3',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-6',
    tenantId: 'tenant-demo-001',
    name: '渡辺由美',
    email: 'watanabe@example.com',
    department: '総務部',
    position: '一般職',
    roles: ['employee'],
    status: 'active',
    phone: '090-1234-5006',
    hireDate: '2022-04-01',
    unitId: 'unit-3',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-7',
    tenantId: 'tenant-demo-001',
    name: '高橋直樹',
    email: 'takahashi@example.com',
    department: '経理部',
    position: '部長',
    roles: ['manager'],
    status: 'active',
    phone: '090-1234-5007',
    hireDate: '2015-04-01',
    unitId: 'unit-4',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-8',
    tenantId: 'tenant-demo-001',
    name: '小林恵子',
    email: 'kobayashi@example.com',
    department: '人事部',
    position: 'マネージャー',
    roles: ['hr'],
    status: 'active',
    phone: '090-1234-5008',
    hireDate: '2019-10-01',
    unitId: 'unit-5',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-9',
    tenantId: 'tenant-demo-001',
    name: '加藤修',
    email: 'kato@example.com',
    department: 'マーケティング部',
    position: 'リーダー',
    roles: ['employee'],
    status: 'active',
    phone: '090-1234-5009',
    hireDate: '2020-07-01',
    unitId: 'unit-6',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-10',
    tenantId: 'tenant-demo-001',
    name: '吉田真一',
    email: 'yoshida@example.com',
    department: '開発部',
    position: 'エンジニア',
    roles: ['employee'],
    status: 'active',
    phone: '090-1234-5010',
    hireDate: '2021-10-01',
    unitId: 'unit-1',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-11',
    tenantId: 'tenant-demo-001',
    name: '中村美穂',
    email: 'nakamura@example.com',
    department: 'デザイン部',
    position: 'デザイナー',
    roles: ['employee'],
    status: 'active',
    phone: '090-1234-5011',
    hireDate: '2022-01-01',
    unitId: 'unit-7',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-12',
    tenantId: 'tenant-demo-001',
    name: '木村拓也',
    email: 'kimura@example.com',
    department: 'デザイン部',
    position: 'アートディレクター',
    roles: ['manager'],
    status: 'active',
    phone: '090-1234-5012',
    hireDate: '2020-04-01',
    unitId: 'unit-7',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-13',
    tenantId: 'tenant-demo-001',
    name: '林真理子',
    email: 'hayashi@example.com',
    department: 'マーケティング部',
    position: 'マーケター',
    roles: ['employee'],
    status: 'active',
    phone: '090-1234-5013',
    hireDate: '2021-07-01',
    unitId: 'unit-6',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-14',
    tenantId: 'tenant-demo-001',
    name: '斎藤健',
    email: 'saito@example.com',
    department: '営業部',
    position: '営業',
    roles: ['employee'],
    status: 'active',
    phone: '090-1234-5014',
    hireDate: '2023-04-01',
    unitId: 'unit-2',
    timezone: 'Asia/Tokyo',
  },
  {
    id: 'user-15',
    tenantId: 'tenant-demo-001',
    name: '松本美香',
    email: 'matsumoto@example.com',
    department: '人事部',
    position: '採用担当',
    roles: ['hr'],
    status: 'active',
    phone: '090-1234-5015',
    hireDate: '2022-10-01',
    unitId: 'unit-5',
    timezone: 'Asia/Tokyo',
  },
];

/**
 * ユーザーストアを初期化
 */
export function initializeUserMockData(addUser: (user: User) => void) {
  mockUsers.forEach((user) => {
    addUser(user);
  });
}
