import { EmployeeSalaryMaster, INSURANCE_RATES } from './types';

// 50名の従業員マスタデータ
export const initialSalaryMasters: EmployeeSalaryMaster[] = [
  {
    id: '1',
    employeeId: 'demo-user-1',
    employeeName: '田中太郎',
    department: '営業部',
    position: '部長',
    basicSalary: 550000,
    positionAllowance: 100000,
    skillAllowance: 30000,
    housingAllowance: 40000,
    familyAllowance: 30000,
    commutingAllowance: 15000,
    hourlyRate: 3500,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 45000,
    unionFee: 3000,
    savingsAmount: 20000,
    dependents: 2, // 配偶者+子供1人
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    employeeId: 'user-2',
    employeeName: '佐藤花子',
    department: '経理部',
    position: '主任',
    basicSalary: 380000,
    positionAllowance: 30000,
    skillAllowance: 15000,
    housingAllowance: 25000,
    familyAllowance: 10000,
    commutingAllowance: 12000,
    hourlyRate: 2400,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 24000,
    savingsAmount: 10000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    employeeId: 'user-3',
    employeeName: '鈴木一郎',
    department: '技術部',
    position: '課長',
    basicSalary: 480000,
    positionAllowance: 60000,
    skillAllowance: 40000,
    housingAllowance: 30000,
    familyAllowance: 30000,
    commutingAllowance: 18000,
    hourlyRate: 3200,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 38000,
    unionFee: 2500,
    loanRepayment: 15000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '4',
    employeeId: 'user-4',
    employeeName: '高橋美咲',
    department: '人事部',
    position: 'スタッフ',
    basicSalary: 280000,
    positionAllowance: 0,
    skillAllowance: 10000,
    housingAllowance: 20000,
    familyAllowance: 0,
    commutingAllowance: 15000,
    hourlyRate: 1900,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 16000,
    savingsAmount: 5000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '5',
    employeeId: 'user-5',
    employeeName: '渡辺健太',
    department: '営業部',
    position: 'スタッフ',
    basicSalary: 350000,
    positionAllowance: 20000,
    skillAllowance: 15000,
    housingAllowance: 25000,
    familyAllowance: 20000,
    commutingAllowance: 10000,
    hourlyRate: 2300,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 22000,
    unionFee: 2000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '6',
    employeeId: 'user-6',
    employeeName: '山田雅子',
    department: '総務部',
    position: '課長',
    basicSalary: 420000,
    positionAllowance: 50000,
    skillAllowance: 20000,
    housingAllowance: 30000,
    familyAllowance: 15000,
    commutingAllowance: 14000,
    hourlyRate: 2800,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 30000,
    unionFee: 2500,
    savingsAmount: 15000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '7',
    employeeId: 'user-7',
    employeeName: '伊藤幸子',
    department: '広報部',
    position: 'スタッフ',
    basicSalary: 320000,
    positionAllowance: 0,
    skillAllowance: 25000,
    housingAllowance: 22000,
    familyAllowance: 10000,
    commutingAllowance: 13000,
    hourlyRate: 2100,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 19000,
    savingsAmount: 8000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '8',
    employeeId: 'user-8',
    employeeName: '小林直樹',
    department: '法務部',
    position: '主任',
    basicSalary: 450000,
    positionAllowance: 40000,
    skillAllowance: 35000,
    housingAllowance: 35000,
    familyAllowance: 25000,
    commutingAllowance: 16000,
    hourlyRate: 3000,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 32000,
    unionFee: 3000,
    savingsAmount: 18000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '9',
    employeeId: 'user-9',
    employeeName: '加藤明美',
    department: '企画部',
    position: 'スタッフ',
    basicSalary: 290000,
    positionAllowance: 0,
    skillAllowance: 12000,
    housingAllowance: 18000,
    familyAllowance: 0,
    commutingAllowance: 9000,
    hourlyRate: 1950,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 17000,
    savingsAmount: 6000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '10',
    employeeId: 'user-10',
    employeeName: '斎藤隆',
    department: '技術部',
    position: '部長',
    basicSalary: 500000,
    positionAllowance: 80000,
    skillAllowance: 50000,
    housingAllowance: 40000,
    familyAllowance: 30000,
    commutingAllowance: 20000,
    hourlyRate: 3300,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 40000,
    unionFee: 3500,
    savingsAmount: 25000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '11',
    employeeId: 'user-11',
    employeeName: '中村優子',
    department: '経理部',
    position: 'スタッフ',
    basicSalary: 310000,
    positionAllowance: 0,
    skillAllowance: 18000,
    housingAllowance: 20000,
    familyAllowance: 15000,
    commutingAllowance: 11000,
    hourlyRate: 2050,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 18500,
    savingsAmount: 7000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '12',
    employeeId: 'user-12',
    employeeName: '森田健一',
    department: '営業部',
    position: '課長',
    basicSalary: 480000,
    positionAllowance: 60000,
    skillAllowance: 30000,
    housingAllowance: 32000,
    familyAllowance: 25000,
    commutingAllowance: 18000,
    hourlyRate: 3200,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 35000,
    unionFee: 2800,
    savingsAmount: 20000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '13',
    employeeId: 'user-13',
    employeeName: '吉田美穂',
    department: '人事部',
    position: '主任',
    basicSalary: 390000,
    positionAllowance: 35000,
    skillAllowance: 22000,
    housingAllowance: 28000,
    familyAllowance: 20000,
    commutingAllowance: 15000,
    hourlyRate: 2600,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 26000,
    unionFee: 2200,
    savingsAmount: 12000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '14',
    employeeId: 'user-14',
    employeeName: '橋本大輔',
    department: '総務部',
    position: 'スタッフ',
    basicSalary: 340000,
    positionAllowance: 15000,
    skillAllowance: 20000,
    housingAllowance: 25000,
    familyAllowance: 10000,
    commutingAllowance: 12000,
    hourlyRate: 2250,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 20500,
    savingsAmount: 9000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '15',
    employeeId: 'user-15',
    employeeName: '西田恵理',
    department: '広報部',
    position: '課長',
    basicSalary: 410000,
    positionAllowance: 45000,
    skillAllowance: 28000,
    housingAllowance: 30000,
    familyAllowance: 20000,
    commutingAllowance: 17000,
    hourlyRate: 2750,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 28500,
    unionFee: 2600,
    savingsAmount: 14000,
    updatedAt: new Date().toISOString(),
  },
  // user-16 ~ user-50 (35名追加)
  {
    id: '16',
    employeeId: 'user-16',
    employeeName: '岡田聡',
    department: '営業部',
    position: 'スタッフ',
    basicSalary: 330000,
    positionAllowance: 10000,
    skillAllowance: 15000,
    housingAllowance: 22000,
    familyAllowance: 10000,
    commutingAllowance: 11000,
    hourlyRate: 2200,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 21000,
    savingsAmount: 8000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '17',
    employeeId: 'user-17',
    employeeName: '松井由香',
    department: '経理部',
    position: 'スタッフ',
    basicSalary: 300000,
    positionAllowance: 0,
    skillAllowance: 12000,
    housingAllowance: 20000,
    familyAllowance: 0,
    commutingAllowance: 10000,
    hourlyRate: 2000,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 18000,
    savingsAmount: 6000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '18',
    employeeId: 'user-18',
    employeeName: '野村健',
    department: '技術部',
    position: 'エンジニア',
    basicSalary: 420000,
    positionAllowance: 30000,
    skillAllowance: 35000,
    housingAllowance: 28000,
    familyAllowance: 20000,
    commutingAllowance: 15000,
    hourlyRate: 2800,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 29000,
    unionFee: 2400,
    savingsAmount: 13000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '19',
    employeeId: 'user-19',
    employeeName: '池田真理',
    department: '人事部',
    position: 'スタッフ',
    basicSalary: 295000,
    positionAllowance: 0,
    skillAllowance: 10000,
    housingAllowance: 18000,
    familyAllowance: 0,
    commutingAllowance: 9000,
    hourlyRate: 1950,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 17500,
    savingsAmount: 5000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '20',
    employeeId: 'user-20',
    employeeName: '久保田修',
    department: '総務部',
    position: 'スタッフ',
    basicSalary: 315000,
    positionAllowance: 10000,
    skillAllowance: 15000,
    housingAllowance: 22000,
    familyAllowance: 15000,
    commutingAllowance: 12000,
    hourlyRate: 2100,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 19500,
    savingsAmount: 7000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '21',
    employeeId: 'user-21',
    employeeName: '前田亮',
    department: '営業部',
    position: '主任',
    basicSalary: 400000,
    positionAllowance: 35000,
    skillAllowance: 20000,
    housingAllowance: 28000,
    familyAllowance: 20000,
    commutingAllowance: 16000,
    hourlyRate: 2650,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 27000,
    unionFee: 2300,
    savingsAmount: 11000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '22',
    employeeId: 'user-22',
    employeeName: '藤原美穂',
    department: '広報部',
    position: 'スタッフ',
    basicSalary: 325000,
    positionAllowance: 0,
    skillAllowance: 22000,
    housingAllowance: 23000,
    familyAllowance: 10000,
    commutingAllowance: 13000,
    hourlyRate: 2150,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 20000,
    savingsAmount: 8500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '23',
    employeeId: 'user-23',
    employeeName: '石川浩二',
    department: '法務部',
    position: 'スタッフ',
    basicSalary: 380000,
    positionAllowance: 25000,
    skillAllowance: 30000,
    housingAllowance: 26000,
    familyAllowance: 15000,
    commutingAllowance: 14000,
    hourlyRate: 2500,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 25000,
    unionFee: 2100,
    savingsAmount: 10000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '24',
    employeeId: 'user-24',
    employeeName: '坂本愛',
    department: '企画部',
    position: 'スタッフ',
    basicSalary: 305000,
    positionAllowance: 0,
    skillAllowance: 15000,
    housingAllowance: 20000,
    familyAllowance: 0,
    commutingAllowance: 10000,
    hourlyRate: 2000,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 18500,
    savingsAmount: 6500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '25',
    employeeId: 'user-25',
    employeeName: '近藤誠',
    department: '技術部',
    position: 'シニアエンジニア',
    basicSalary: 500000,
    positionAllowance: 70000,
    skillAllowance: 45000,
    housingAllowance: 38000,
    familyAllowance: 30000,
    commutingAllowance: 19000,
    hourlyRate: 3300,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 38000,
    unionFee: 3200,
    savingsAmount: 22000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '26',
    employeeId: 'user-26',
    employeeName: '村上綾香',
    department: '経理部',
    position: '主任',
    basicSalary: 395000,
    positionAllowance: 33000,
    skillAllowance: 20000,
    housingAllowance: 27000,
    familyAllowance: 15000,
    commutingAllowance: 14000,
    hourlyRate: 2600,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 26500,
    unionFee: 2250,
    savingsAmount: 11500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '27',
    employeeId: 'user-27',
    employeeName: '竹内隆史',
    department: '営業部',
    position: 'スタッフ',
    basicSalary: 345000,
    positionAllowance: 15000,
    skillAllowance: 18000,
    housingAllowance: 24000,
    familyAllowance: 10000,
    commutingAllowance: 12000,
    hourlyRate: 2250,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 22500,
    savingsAmount: 9000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '28',
    employeeId: 'user-28',
    employeeName: '須藤麗',
    department: '人事部',
    position: '課長',
    basicSalary: 460000,
    positionAllowance: 55000,
    skillAllowance: 25000,
    housingAllowance: 32000,
    familyAllowance: 25000,
    commutingAllowance: 17000,
    hourlyRate: 3050,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 33000,
    unionFee: 2700,
    savingsAmount: 16000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '29',
    employeeId: 'user-29',
    employeeName: '宮崎太一',
    department: '総務部',
    position: '主任',
    basicSalary: 385000,
    positionAllowance: 30000,
    skillAllowance: 18000,
    housingAllowance: 26000,
    familyAllowance: 20000,
    commutingAllowance: 13000,
    hourlyRate: 2550,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 25500,
    unionFee: 2150,
    savingsAmount: 10500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '30',
    employeeId: 'user-30',
    employeeName: '大野由紀',
    department: '広報部',
    position: 'スタッフ',
    basicSalary: 335000,
    positionAllowance: 0,
    skillAllowance: 20000,
    housingAllowance: 23000,
    familyAllowance: 0,
    commutingAllowance: 12000,
    hourlyRate: 2200,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 21000,
    savingsAmount: 8500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '31',
    employeeId: 'user-31',
    employeeName: '谷口信夫',
    department: '法務部',
    position: '課長',
    basicSalary: 470000,
    positionAllowance: 58000,
    skillAllowance: 38000,
    housingAllowance: 34000,
    familyAllowance: 25000,
    commutingAllowance: 18000,
    hourlyRate: 3100,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 34000,
    unionFee: 2850,
    savingsAmount: 17000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '32',
    employeeId: 'user-32',
    employeeName: '西村香織',
    department: '企画部',
    position: '主任',
    basicSalary: 375000,
    positionAllowance: 28000,
    skillAllowance: 16000,
    housingAllowance: 25000,
    familyAllowance: 10000,
    commutingAllowance: 13000,
    hourlyRate: 2450,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 24500,
    unionFee: 2050,
    savingsAmount: 10000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '33',
    employeeId: 'user-33',
    employeeName: '上田拓也',
    department: '技術部',
    position: 'エンジニア',
    basicSalary: 410000,
    positionAllowance: 32000,
    skillAllowance: 33000,
    housingAllowance: 29000,
    familyAllowance: 15000,
    commutingAllowance: 16000,
    hourlyRate: 2700,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 28000,
    unionFee: 2350,
    savingsAmount: 12500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '34',
    employeeId: 'user-34',
    employeeName: '金子美和',
    department: '経理部',
    position: '課長',
    basicSalary: 465000,
    positionAllowance: 56000,
    skillAllowance: 27000,
    housingAllowance: 33000,
    familyAllowance: 20000,
    commutingAllowance: 17000,
    hourlyRate: 3080,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 33500,
    unionFee: 2750,
    savingsAmount: 16500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '35',
    employeeId: 'user-35',
    employeeName: '三浦健太郎',
    department: '営業部',
    position: 'スタッフ',
    basicSalary: 325000,
    positionAllowance: 12000,
    skillAllowance: 14000,
    housingAllowance: 22000,
    familyAllowance: 10000,
    commutingAllowance: 11000,
    hourlyRate: 2150,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 20500,
    savingsAmount: 8000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '36',
    employeeId: 'user-36',
    employeeName: '内田千鶴',
    department: '人事部',
    position: 'スタッフ',
    basicSalary: 290000,
    positionAllowance: 0,
    skillAllowance: 11000,
    housingAllowance: 19000,
    familyAllowance: 0,
    commutingAllowance: 9500,
    hourlyRate: 1950,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 17500,
    savingsAmount: 5500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '37',
    employeeId: 'user-37',
    employeeName: '今井俊介',
    department: '総務部',
    position: 'スタッフ',
    basicSalary: 320000,
    positionAllowance: 8000,
    skillAllowance: 17000,
    housingAllowance: 21000,
    familyAllowance: 15000,
    commutingAllowance: 11500,
    hourlyRate: 2100,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 20000,
    savingsAmount: 7500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '38',
    employeeId: 'user-38',
    employeeName: '杉本直子',
    department: '広報部',
    position: '主任',
    basicSalary: 390000,
    positionAllowance: 31000,
    skillAllowance: 26000,
    housingAllowance: 27000,
    familyAllowance: 20000,
    commutingAllowance: 15000,
    hourlyRate: 2580,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 26000,
    unionFee: 2200,
    savingsAmount: 11500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '39',
    employeeId: 'user-39',
    employeeName: '横山勇',
    department: '法務部',
    position: 'スタッフ',
    basicSalary: 370000,
    positionAllowance: 23000,
    skillAllowance: 28000,
    housingAllowance: 25000,
    familyAllowance: 10000,
    commutingAllowance: 13500,
    hourlyRate: 2450,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 24000,
    unionFee: 2000,
    savingsAmount: 9500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '40',
    employeeId: 'user-40',
    employeeName: '水野沙織',
    department: '企画部',
    position: '課長',
    basicSalary: 455000,
    positionAllowance: 54000,
    skillAllowance: 24000,
    housingAllowance: 31000,
    familyAllowance: 25000,
    commutingAllowance: 16500,
    hourlyRate: 3000,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 32000,
    unionFee: 2650,
    savingsAmount: 15500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '41',
    employeeId: 'user-41',
    employeeName: '長野浩',
    department: '技術部',
    position: 'エンジニア',
    basicSalary: 425000,
    positionAllowance: 35000,
    skillAllowance: 36000,
    housingAllowance: 30000,
    familyAllowance: 20000,
    commutingAllowance: 16000,
    hourlyRate: 2800,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 29500,
    unionFee: 2450,
    savingsAmount: 13500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '42',
    employeeId: 'user-42',
    employeeName: '藤井瞳',
    department: '経理部',
    position: 'スタッフ',
    basicSalary: 315000,
    positionAllowance: 0,
    skillAllowance: 16000,
    housingAllowance: 21000,
    familyAllowance: 10000,
    commutingAllowance: 11000,
    hourlyRate: 2080,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 19500,
    savingsAmount: 7000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '43',
    employeeId: 'user-43',
    employeeName: '本田雅彦',
    department: '営業部',
    position: '主任',
    basicSalary: 405000,
    positionAllowance: 36000,
    skillAllowance: 21000,
    housingAllowance: 28000,
    familyAllowance: 20000,
    commutingAllowance: 15500,
    hourlyRate: 2670,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 27500,
    unionFee: 2350,
    savingsAmount: 12000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '44',
    employeeId: 'user-44',
    employeeName: '安藤理恵',
    department: '人事部',
    position: 'スタッフ',
    basicSalary: 298000,
    positionAllowance: 0,
    skillAllowance: 12000,
    housingAllowance: 19500,
    familyAllowance: 0,
    commutingAllowance: 10000,
    hourlyRate: 1980,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 18000,
    savingsAmount: 6000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '45',
    employeeId: 'user-45',
    employeeName: '柴田浩司',
    department: '総務部',
    position: '部長',
    basicSalary: 530000,
    positionAllowance: 90000,
    skillAllowance: 28000,
    housingAllowance: 40000,
    familyAllowance: 30000,
    commutingAllowance: 19000,
    hourlyRate: 3500,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 42000,
    unionFee: 3300,
    savingsAmount: 23000,
    dependents: 3,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '46',
    employeeId: 'user-46',
    employeeName: '河合あゆみ',
    department: '広報部',
    position: 'スタッフ',
    basicSalary: 330000,
    positionAllowance: 0,
    skillAllowance: 21000,
    housingAllowance: 23000,
    familyAllowance: 0,
    commutingAllowance: 12500,
    hourlyRate: 2170,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 21000,
    savingsAmount: 8500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '47',
    employeeId: 'user-47',
    employeeName: '片岡大輔',
    department: '法務部',
    position: '主任',
    basicSalary: 435000,
    positionAllowance: 38000,
    skillAllowance: 34000,
    housingAllowance: 31000,
    familyAllowance: 25000,
    commutingAllowance: 17000,
    hourlyRate: 2870,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 30000,
    unionFee: 2550,
    savingsAmount: 14500,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '48',
    employeeId: 'user-48',
    employeeName: '橋爪千尋',
    department: '企画部',
    position: 'スタッフ',
    basicSalary: 310000,
    positionAllowance: 0,
    skillAllowance: 14000,
    housingAllowance: 20000,
    familyAllowance: 10000,
    commutingAllowance: 10500,
    hourlyRate: 2050,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 19000,
    savingsAmount: 7000,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '49',
    employeeId: 'user-49',
    employeeName: '岩崎正樹',
    department: '技術部',
    position: '次長',
    basicSalary: 520000,
    positionAllowance: 85000,
    skillAllowance: 48000,
    housingAllowance: 39000,
    familyAllowance: 30000,
    commutingAllowance: 19500,
    hourlyRate: 3430,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 41000,
    unionFee: 3250,
    savingsAmount: 22000,
    dependents: 2,
    updatedAt: new Date().toISOString(),
  },
  {
    id: '50',
    employeeId: 'user-50',
    employeeName: '平野恵美',
    department: '経理部',
    position: '部長',
    basicSalary: 540000,
    positionAllowance: 95000,
    skillAllowance: 32000,
    housingAllowance: 41000,
    familyAllowance: 30000,
    commutingAllowance: 20000,
    hourlyRate: 3570,
    overtimeRate: 1.25,
    lateNightRate: 1.5,
    holidayRate: 1.35,
    healthInsuranceRate: INSURANCE_RATES.health.employee,
    pensionRate: INSURANCE_RATES.pension.employee,
    employmentInsuranceRate: INSURANCE_RATES.employment.employee,
    residentTaxAmount: 43000,
    unionFee: 3400,
    savingsAmount: 24000,
    dependents: 2,
    updatedAt: new Date().toISOString(),
  },
];
